on: [push]
name: 'Bonject.Campaign.API CI/CD'

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - uses: azure/docker-login@v1
          with:
            login-server: bonject.azurecr.io
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}

        - name: 'Build and push'
          working-directory: Bonject.Campaign.API
          run: |
            docker build . -t bonject.azurecr.io/campaign.api:latest
            docker push bonject.azurecr.io/campaign.api:latest
