name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DOCKER_IMAGE_NAME: 'bonject.azurecr.io/campaign.api'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Build'
      run: docker build . --file Dockerfile --tag '${{env.DOCKER_IMAGE_NAME}}':latest
      working-directory: Bonject.Campaign.API

    - name: 'Build and push it'
      working-directory: Bonject.Campaign.API
      run: |
        docker build . --file Dockerfile --tag '${{env.DOCKER_IMAGE_NAME}}':latest
        docker push '${{env.DOCKER_IMAGE_NAME}}':latest
